(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.LLMarioConstruction=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const TYPES=new Set(['terrain','resizable','span','fixed','parametric']);
function entries(c){return c&&c.version===1&&c.families&&typeof c.families==='object'?c.families:{}}
function validate(c){const errors=[];if(!c||c.version!==1)errors.push('constructionCatalog.version must be 1');for(const [id,e] of Object.entries(entries(c))){if(e.id&&e.id!==id)errors.push(id+': id must match key');if(!TYPES.has(e.type))errors.push(id+': unsupported type '+e.type);if(!e.name)errors.push(id+': name is required');if(e.ascii!=null&&typeof e.ascii!=='object')errors.push(id+': ascii must be an object or null');if(e.type==='terrain'&&!((e.components||{}).topologyFallback))errors.push(id+': terrain topologyFallback is required')}return errors}
function clamp(n,min,max){n=Math.round(Number(n)||min);return Math.max(min,Math.min(max==null?Infinity:max,n))}
function part(asset,x,y,w=1,h=1){return {asset,x,y,w,h}}
function pipeLayout(e,height,scale=1){const d=e.dimensions||{},c=e.components||{},worldH=Math.max(0,Number(height)||0),worldW=58*scale,half=worldW/2,capH=Math.min(worldH,Math.max(16*scale,half)),step=16*scale,out=[];for(const p of c.cap||[])out.push(part(p.asset,(p.x||0)*half,0,half,capH));for(let y=capH;y<worldH;y+=step)for(const p of c.body||[])out.push(part(p.asset,(p.x||0)*half,y,half,Math.min(step,worldH-y)));return out.filter(p=>p.asset).map(p=>Object.assign(p,{family:e.id||null}))}
function construct(e,size={}){if(!e)throw Error('unknown construction family');const d=e.dimensions||{},w=clamp(size.w,d.minW||1,d.maxW),h=clamp(size.h,d.minH||1,d.maxH),c=e.components||{},out=[];
 if(e.type==='fixed')for(const p of c.parts||[])out.push(part(p.asset,p.x||0,p.y||0,p.w||1,p.h||1));
 else if(e.type==='span'){if(w===1)out.push(part(c.single||c.middle||c.left,0,0));else{out.push(part(c.left,0,0));for(let x=1;x<w-1;x++)out.push(part(c.middle,x,0));out.push(part(c.right,w-1,0))}}
 else if(e.type==='resizable'&&e.authoringBinding&&e.authoringBinding.noun==='pipe'){
  // Pipes intentionally preserve their established world-space presentation:
  // two 16px source halves stretch across a 58px pipe, while body art repeats
  // vertically at its native scaled step (with a clipped final segment).
  const scale=Number(size.scale)||1,cell=d.cell||16,worldH=Number.isFinite(size.worldH)?size.worldH:h*cell;
  for(const p of pipeLayout(e,worldH,scale))out.push(part(p.asset,p.x/cell,p.y/cell,p.w/cell,p.h/cell));
 }
 else if(e.type==='resizable'){for(const p of c.cap||[])out.push(part(p.asset,p.x||0,p.y||0));for(let y=1;y<h;y++)for(const p of c.body||[])out.push(part(p.asset,p.x||0,y));}
 else if(e.type==='parametric'){const cap=c.cap||{};if(w===1)out.push(part(cap.single||cap.middle,0,0));else{out.push(part(cap.left,0,0));for(let x=1;x<w-1;x++)out.push(part(cap.middle,x,0));out.push(part(cap.right,w-1,0))}const stem=c.stem||{};for(let y=1;y<h;y++)for(let x=0;x<w;x++){const r=x===0?stem.left:x===w-1?stem.right:stem.middle;if(r)out.push(part(r,x,y))}}
 return out.filter(p=>p.asset).map(p=>Object.assign(p,{family:e.id||null}));
}
function terrainRole(e,cells,x,y){const has=(dx,dy)=>cells.has((x+dx)+','+(y+dy)),key=[[0,-1],[1,0],[0,1],[-1,0]].map(q=>Number(has(...q))).join(''),c=e.components||{},role=(c.topology||{})[key];if(role)return {asset:role,key,fallback:false};const fb=c.topologyFallback;if(!fb)return null;return {asset:fb.asset||null,key,fallback:true,strategy:fb.strategy||'procedural'}}
function affectedCells(changed){const out=new Set();for(const q of changed){const [x,y]=typeof q==='string'?q.split(',').map(Number):[q.x,q.y];for(const [dx,dy] of [[0,0],[0,-1],[1,0],[0,1],[-1,0]])out.add((x+dx)+','+(y+dy))}return out}
function terrainStrokeCells(points,cell=16){const out=new Set(),pts=points||[],size=Math.max(1,Number(cell)||16),at=p=>[Math.floor(Number(p.x)/size),Math.floor(Number(p.y)/size)];for(let i=0;i<pts.length;i++){let [x0,y0]=at(i?pts[i-1]:pts[i]);if(!i){out.add(x0+','+y0);continue}const [x1,y1]=at(pts[i]),dx=Math.abs(x1-x0),dy=Math.abs(y1-y0),sx=x0<x1?1:-1,sy=y0<y1?1:-1;let err=dx-dy;for(;;){out.add(x0+','+y0);if(x0===x1&&y0===y1)break;const e2=2*err;if(e2>-dy){err-=dy;x0+=sx}if(e2<dx){err+=dx;y0+=sy}}}return out}
function resolveTerrain(e,cells,changed){const affected=affectedCells(changed||cells),out=[];for(const k of [...affected].sort()){if(!cells.has(k))continue;const [x,y]=k.split(',').map(Number),r=terrainRole(e,cells,x,y);if(r)out.push({family:e.id,asset:r.asset,topology:r.key,fallback:r.fallback,fallbackStrategy:r.strategy,x,y,w:1,h:1})}return out}
function asciiMaps(c){const imports={},exports={};for(const [id,e] of Object.entries(entries(c))){if(!e.ascii)continue;if(e.ascii.import)imports[e.ascii.import]=id;if(e.ascii.export)exports[id]=e.ascii.export}return {imports,exports}}
function proceduralStyle(theme,family){const e=entries(theme&&theme.constructionCatalog)[family]||{},fb=(e.components||{}).topologyFallback||{},s=fb.style||{};return {fill:s.fill||'#75451f',top:s.top||'#6abf31',topRatio:Number.isFinite(s.topRatio)?s.topRatio:0.3125,stroke:s.stroke||'rgba(0,0,0,.45)'}}
function drawProceduralTerrain(ctx,box,style){ctx.save();ctx.fillStyle=style.fill;ctx.fillRect(box.x,box.y,box.w,box.h);ctx.fillStyle=style.top;ctx.fillRect(box.x,box.y,box.w,Math.max(1,box.h*style.topRatio));ctx.strokeStyle=style.stroke;ctx.strokeRect(box.x,box.y,box.w,box.h);ctx.restore()}
function pathParts(path){return Array.isArray(path)?path:String(path||'').split('.').filter(Boolean)}
function arrayAtPath(root,path,create=false){const parts=pathParts(path);let at=root;for(let i=0;i<parts.length;i++){const key=parts[i],last=i===parts.length-1;if(last){if(!Array.isArray(at[key])&&create)at[key]=[];return Array.isArray(at[key])?at[key]:null}if(!at[key]||typeof at[key]!=='object'){if(!create)return null;at[key]={}}at=at[key]}return null}
function findBinding(root,entry,group){const arr=arrayAtPath(root,entry&&entry.authoringBinding&&entry.authoringBinding.path,false);return arr&&arr.find(o=>o&&o.constructionGroup===group&&!o.image)||null}
function ensureBinding(root,entry,group,base={}){const b=entry&&entry.authoringBinding;if(!b)return null;const arr=arrayAtPath(root,b.path,true);let found=findBinding(root,entry,group);if(!found){found=Object.assign({},b.defaults||{},base,{constructionGroup:group,constructionBinding:b.noun});arr.push(found)}return found}
function updateBinding(root,entry,group,origin,size,base={}){const b=entry&&entry.authoringBinding,o=ensureBinding(root,entry,group,base);if(!o)return null;const cell=(entry.dimensions||{}).cell||16,w=size.w,h=size.h;if(b.noun==='pipe'){const worldH=Number.isFinite(size.worldH)?size.worldH:h*cell;o.kind='pipe';o.direction='up';o.x=origin.x;o.y=origin.y+worldH;o.length=worldH;o.h=worldH;o.scale=Number(size.scale)||1;o.solid=o.solid!==false;o.resolvedVisuals=true}else if(b.noun==='climbZone'){o.kind='ladder';o.x=origin.x;o.y=origin.y;o.w=w*cell;o.h=h*cell;o.anchorX=0;o.anchorY=0;o.climbable=true;o.collision={kind:'climb'};o.alpha=0;o.resolvedVisuals=true}return o}
function remapConstructionGroups(items,idFactory){const ids=new Map();for(const item of items||[]){const o=item&&item.obj||item,g=o&&o.constructionGroup;if(!g)continue;if(!ids.has(g))ids.set(g,idFactory(g));o.constructionGroup=ids.get(g)}return ids}
function asciiCellsToNative(cells,origin,asciiCell,nativeCell){const out=new Set(),ox=Number(origin.x)||0,oy=Number(origin.y)||0;for(const q of cells){const x=typeof q==='string'?Number(q.split(',')[0]):q.x,y=typeof q==='string'?Number(q.split(',')[1]):q.y,left=ox+x*asciiCell,right=left+asciiCell,top=oy+y*asciiCell,bottom=top+asciiCell;let x0=Math.ceil((left-nativeCell/2)/nativeCell),x1=Math.floor((right-1e-9-nativeCell/2)/nativeCell),y0=Math.ceil((top-nativeCell/2)/nativeCell),y1=Math.floor((bottom-1e-9-nativeCell/2)/nativeCell);if(x1<x0)x0=x1=Math.round(((left+right)/2-nativeCell/2)/nativeCell);if(y1<y0)y0=y1=Math.round(((top+bottom)/2-nativeCell/2)/nativeCell);for(let ny=y0;ny<=y1;ny++)for(let nx=x0;nx<=x1;nx++)out.add(nx+','+ny)}return out}
function selectedGroupBindings(selection,all,noun){const groups=[],seen=new Set();for(const item of selection||[]){const o=item&&item.obj||item,g=o&&o.constructionGroup;if(g&&!seen.has(g)){seen.add(g);groups.push(g)}}return groups.map(g=>(all||[]).find(item=>{const o=item&&item.obj||item;return o&&o.constructionGroup===g&&o.constructionBinding===noun&&!o.image})).filter(Boolean)}
function logicalSelection(selection,all,noun,isOrdinary){const out=[],seen=new Set();for(const item of selection||[]){const o=item&&item.obj||item;let logical=null;if(isOrdinary(item)&&!o.image)logical=item;else if(o.constructionGroup)logical=(all||[]).find(candidate=>{const c=candidate&&candidate.obj||candidate;return c&&c.constructionGroup===o.constructionGroup&&c.constructionBinding===noun&&!c.image});if(logical){const value=logical&&logical.obj||logical;if(!seen.has(value)){seen.add(value);out.push(logical)}}}return out}
function terrainOccupancy(sprites,family){return new Set((sprites||[]).filter(s=>s.semanticFamily===family&&Number.isFinite(s.semanticCellX)&&Number.isFinite(s.semanticCellY)).map(s=>s.semanticCellX+','+s.semanticCellY))}
function applyTerrainEdit(state,e,changed,paint=true){const sprites=state.sprites||[],collisions=state.collisions||[],cells=terrainOccupancy(sprites,e.id);for(const k of changed)paint?cells.add(k):cells.delete(k);const affected=affectedCells(changed),cell=(e.dimensions||{}).cell||16,manual=new Set(sprites.filter(s=>s.semanticFamily===e.id&&s.semanticAuto===false).map(s=>s.semanticCellX+','+s.semanticCellY));if(!paint)for(const k of changed)manual.delete(k);state.sprites=sprites.filter(s=>!(s.semanticFamily===e.id&&affected.has(s.semanticCellX+','+s.semanticCellY)&&!manual.has(s.semanticCellX+','+s.semanticCellY)));state.collisions=collisions.filter(s=>!(s.semanticFamily===e.id&&affected.has(s.semanticCellX+','+s.semanticCellY)&&!manual.has(s.semanticCellX+','+s.semanticCellY)));for(const p of resolveTerrain(e,cells,affected)){const k=p.x+','+p.y;if(manual.has(k))continue;state.sprites.push({semanticFamily:e.id,semanticAuto:true,image:p.asset,semanticTopology:p.topology,semanticFallback:p.fallbackStrategy||null,semanticCellX:p.x,semanticCellY:p.y,x:p.x*cell,y:p.y*cell,w:cell,h:cell,anchorX:0,anchorY:0,visualOnly:true,layer:'back'});state.collisions.push({semanticFamily:e.id,semanticAuto:true,semanticCellX:p.x,semanticCellY:p.y,x:p.x*cell,y:p.y*cell,w:cell,h:cell,type:'ground',collisionOnly:true})}return state}
return {validate,construct,pipeLayout,resolveTerrain,terrainRole,terrainStrokeCells,asciiMaps,proceduralStyle,drawProceduralTerrain,arrayAtPath,findBinding,ensureBinding,updateBinding,remapConstructionGroups,asciiCellsToNative,selectedGroupBindings,logicalSelection,terrainOccupancy,affectedCells,applyTerrainEdit};
});
