'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),C=require('../construction/catalog.js');
const editor=fs.readFileSync('archived/editor/editor.html','utf8'),engine=fs.readFileSync('engine/engine.html','utf8');
function fn(source,name){const start=source.indexOf('function '+name+'(');assert(start>=0,'missing '+name);let paren=source.indexOf('(',start),pd=0,brace=-1;for(let i=paren;i<source.length;i++){if(source[i]==='(')pd++;else if(source[i]===')'&&!--pd){brace=source.indexOf('{',i);break}}let depth=0,quote='',escape=false;for(let i=brace;i<source.length;i++){const ch=source[i];if(quote){if(escape)escape=false;else if(ch==='\\')escape=true;else if(ch===quote)quote='';continue}if(ch==='"'||ch==="'"||ch==='`'){quote=ch;continue}if(ch==='{')depth++;else if(ch==='}'&&!--depth)return source.slice(start,i+1)}throw Error('unterminated '+name)}
function load(c,source,names){vm.runInContext(names.map(n=>fn(source,n)).join('\n'),c)}
const clone=x=>JSON.parse(JSON.stringify(x)),plain=x=>!!x&&typeof x==='object'&&!Array.isArray(x);
function merge(a,b){if(Array.isArray(b))return clone(b);if(plain(b)){const o=plain(a)?clone(a):{};for(const k of Object.keys(b))o[k]=merge(o[k],b[k]);return o}return b===undefined?clone(a):b}
const theme=JSON.parse(fs.readFileSync('archived/themes/theme_marioai_nonempty.llmtheme.txt','utf8'));

// Stamp is the sole persistent terrain-paint state; brush changes preserve it.
let status='';const button={classList:{toggle(){}},textContent:''},terrainButton={classList:{remove(){}}};
let c=vm.createContext({stampMode:false,terrainStrokeMode:false,terrainEraseMode:false,paletteWasSemantic:false,els:{stampMode:button,terrainStroke:terrainButton,insertKind:{value:'construction:terrain.overground'}},activeSemanticTerrain:()=>({id:'terrain.overground'}),updateTopStatus:()=>{},setStatus:s=>status=s,updateActiveBrush:()=>{},populatePalette:()=>{},clearTerrainErase:()=>{},isOrdinaryPlatformBrush:()=>false});
load(c,editor,['setStampMode','paletteSelectionChanged']);vm.runInContext('setStampMode',c)(true);assert.equal(c.stampMode,true);assert.match(status,/paint terrain/);vm.runInContext('paletteSelectionChanged',c)();assert.equal(c.stampMode,true);
const pointer=editor.slice(editor.indexOf("canvas.addEventListener('pointerdown'"),editor.indexOf("addEventListener('pointermove'"));assert(pointer.includes('if(stampMode&&semantic)'));assert(pointer.indexOf("if(e.button===0&&spacePanHeld)")<pointer.indexOf('if(stampMode&&semantic)'));assert(!pointer.includes('if(semantic){'));
assert(pointer.includes('if(!completeConstructionSelected(hit))select(hit)'),'left-drag promotes a partial construction selection to its complete group');
const pieceA={obj:{x:101,y:53,constructionGroup:'pipe'},path:['sprites',0]},pieceB={obj:{x:130,y:82,constructionGroup:'pipe'},path:['sprites',1]};c=vm.createContext({objects:[pieceA,pieceB],selection:[pieceA],pathKey:p=>p.join('.'),grid:()=>24,roundish:v=>Math.round(v*100)/100,visualSize:()=>({w:0,h:0}),anchorFor:()=>({x:0,y:0}),isHitboxHelper:()=>false});load(c,editor,['isSelected','completeConstructionSelected','snap','snapPoint','setObjectRectXY','moveRigid']);assert.equal(vm.runInContext('completeConstructionSelected',c)(pieceA),false,'one preselected pipe piece is not a complete construction selection');c.selection.push(pieceB);assert.equal(vm.runInContext('completeConstructionSelected',c)(pieceA),true,'the complete pipe group is recognized');const moved=[{it:pieceA,r:{x:101,y:53}},{it:pieceB,r:{x:130,y:82}}];vm.runInContext('moveRigid',c)(moved,0,0,true);assert.deepEqual(moved.map(s=>[s.it.obj.x,s.it.obj.y]),[[96,48],[125,77]],'group drag snapping preserves the canonical 29px pipe offset');
const keys=editor.slice(editor.indexOf("addEventListener('keydown'"),editor.indexOf("addEventListener('keyup'"));assert(keys.includes("e.key==='Escape'"));assert(keys.indexOf("e.key==='Escape'")<keys.indexOf('if(active)return'));const escapeBranch=keys.slice(keys.indexOf("if(e.key==='Escape'"),keys.indexOf('if(active)return'));assert(!escapeBranch.includes('preventDefault'));for(const action of ['drag=null','terrainStrokeMode=false','clearTerrainErase()','setStampMode(false)'])assert(keys.includes(action));assert(keys.includes("e.key.toLowerCase()==='s'"));

// Paint through the real editor integration point, then preserve its paired records end to end.
const terrain=theme.constructionCatalog.families['terrain.overground'],authored={id:'tiny',title:'Tiny',theme:theme.id,world:{width:320,groundY:240},playerSpawn:{x:32,y:16},resourceScenery:{sprites:[]},platforms:[],floatingBlocks:[],coins:[],stars:[],enemies:[],signposts:[],portal:{x:280,y:160,w:32,h:64}};
c=vm.createContext({cart:authored,themePack:theme,fileName:'tiny',window:{LLMarioConstruction:C},LLMarioConstruction:C,terrainEraseMode:false,els:{terrainAuto:{checked:true}},objects:[],num:(v,d)=>Number.isFinite(Number(v))?Number(v):d,ensureArray:path=>path.reduce((at,key)=>(at[key]||(at[key]=[])),authored),saveUndo:()=>{},rebuild:()=>{},setSelection:()=>{},draw:()=>{},setStatus:()=>{},cleanExportBaseName:x=>x,plain});load(c,editor,['commitSemanticTerrain','themeIdFromSource','buildThinMapFromCart']);vm.runInContext('commitSemanticTerrain',c)(new Set(['2,3']),{id:'terrain.overground',entry:terrain});assert.equal(authored.resourceScenery.sprites.length,1);assert.equal(authored.platforms.length,1);assert.equal(authored.resourceScenery.sprites[0].visualOnly,true);assert.equal(authored.platforms[0].collisionOnly,true);const map=vm.runInContext('buildThinMapFromCart',c)(authored);assert.equal(map.platforms[0].collisionOnly,true);
const defaults={defaults:{volume:1},sfx:{jump:[{role:'lead'}],coin:[{role:'bell'}],star:[{role:'bell'}]}};
c=vm.createContext({console,JSON,ENGINE_DEFAULT_AUDIO:defaults,LEVEL_FUNDAMENTALS:{},PENDING_MAP_LABEL:'tiny',isThemeDoc:x=>x.format==='llmario-theme-pack-v1',isMapDoc:x=>x.format==='llmario-map-v1',mapThemeIdOf:x=>x.theme,themeIdOf:x=>x.id,cloneData:clone,mergeCartValue:merge,normalizeMapMessages:x=>x.messages||{},isPlainObject:plain,finiteNumber:Number.isFinite,truthForCartAsset:()=>null,collisionKind:x=>String(x&&x.kind||''),platformTruthId:()=>null,normalizeCartridgePlacements:x=>x,DEMO_CART:{}});load(c,engine,['convertTruthSlopePlatformsToSprites','buildCartFromThemeAndMap','normalizeCart']);const built=vm.runInContext('buildCartFromThemeAndMap',c)(theme,map),normalized=vm.runInContext('normalizeCart',c)(built);assert.equal(normalized.platforms[0].collisionOnly,true);assert.equal(normalized.platforms[0].semanticFamily,'terrain.overground');
const runtimePlatforms=[];Object.assign(c,{ACTIVE_CART:{},buildSemanticAssetIndex:()=>({ids:[],bySuffix:{}}),inferredAnimationGroups:()=>({}),WORLD_W:0,GROUND_Y:0,loadCartImageAssets:()=>{},platforms:runtimePlatforms,floatingBlocks:[],coins:[],stars:[],enemies:[],signposts:[],freshEnemy:x=>x,portal:{},powerups:[],projectiles:[],coinBursts:[],blockBursts:[],player:{},toastLines:[],gameAudio:{cartAudio:null,setParams(p){this.params=p}},reset:()=>{}});load(c,engine,['replaceArray','rebuildWorldFromCart']);vm.runInContext('rebuildWorldFromCart',c)(normalized);assert.equal(runtimePlatforms.length,1);assert.equal(runtimePlatforms[0].collisionOnly,true);assert(c.gameAudio.cartAudio.sfx.jump.length&&c.gameAudio.cartAudio.sfx.coin.length);
Object.assign(c,{ACTIVE_CART:normalized,platforms:runtimePlatforms,floatingBlocks:[],aabb:(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y,isSlopePlatform:()=>false,sceneryPipeSolid:()=>null,imageSpriteSolid:()=>null,floatingSolid:()=>null});load(c,engine,['hitSolids']);c.hitSolids=vm.runInContext('hitSolids',c);const solid=runtimePlatforms[0],box={x:solid.x+2,y:solid.y-6,w:8,h:8};assert.equal(c.hitSolids(box)[0].collisionOnly,true);
Object.assign(c,{player:{x:solid.x+2,y:solid.y-12,w:8,h:8,vx:0,vy:6,onGround:false},shallowTopContact:()=>false,slopeExitTopContact:()=>false,resolvePlayerSlopes:()=>{},bonkBlock:()=>{}});load(c,engine,['isOneWayTop','resolvePlayerOneWayTops','resolvePlayer']);vm.runInContext('resolvePlayer',c)();assert.equal(c.player.y,solid.y-c.player.h);assert.equal(c.player.onGround,true);assert.equal(c.player.vy,0);

// Missing theme recipes use engine-owned draw fallbacks without changing hidden helpers.
const calls=[];c=vm.createContext({ACTIVE_CART:{recipes:{},hud:{}},recipe:()=>null,PREFABS:{},worldX:x=>x,W:640,ctx:{fillStyle:'',strokeStyle:'',lineWidth:0,fillRect:(...a)=>calls.push(['fill',...a]),strokeRect:(...a)=>calls.push(['stroke',...a])},isSlopePlatform:()=>false,drawRecipe:()=>false,prefabHud:()=>calls.push(['hud'])});load(c,engine,['drawDefaultPlatform','drawPlatform','drawHUD']);vm.runInContext('drawPlatform',c)({x:10,y:20,w:80,h:30,type:'ground'});vm.runInContext('drawHUD',c)();const before=calls.length;vm.runInContext('drawPlatform',c)({x:0,y:0,w:16,h:16,collisionOnly:true});assert(calls.some(x=>x[0]==='fill'));assert(calls.some(x=>x[0]==='hud'));assert.equal(calls.length,before);assert.deepEqual(clone(built.recipes),clone(theme.recipes));assert(!built.recipes.hero||built.recipes.hero.prefab!=='physicsMascot');
assert(engine.includes('if(p.collisionOnly || p.editorHitbox || p.editorCollisionOnly) continue;'));
console.log('Cartbench / split-theme cohesion tests passed');
