const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('editor/editor.html','utf8');
function fn(name){const m=html.match(new RegExp('function '+name+'\\([^]*?(?=\\nfunction |\\nlet paletteAnimationStep)'));if(!m)throw Error('missing '+name);return m[0]}
const theme=JSON.parse(fs.readFileSync('themes/theme_marioai_nonempty.llmtheme.txt','utf8'));
assert.deepEqual(theme.sceneLayers,['background','world','actors','foreground']);
assert.equal(theme.constructionCatalog.families['bush.span'].authoringGroup,'deco');
assert.equal(theme.constructionCatalog.families['bush.span'].defaultSceneLayer,'background');
assert.equal(theme.constructionCatalog.families['terrain.overground'].authoringGroup,'world');
assert.equal({...theme.constructionCatalog.families['bush.span'],collisionMode:'solid'}.authoringGroup,'deco','group metadata is independent of collision');
const bg=Object.values(theme.assetCatalog).filter(x=>x.sourceSheet==='bgsheet.png');
assert(bg.length&&bg.every(x=>x.authoringGroup==='deco'&&x.paletteExposure==='relationshipOnly'&&x.decoRelationship==='unresolved'));
const c=vm.createContext({themePack:theme,cart:null,visualImageFor:it=>it.obj.image||'',pathKey:p=>p.join('.')});
vm.runInContext([fn('sceneLayerCatalog'),fn('defaultSceneLayer'),fn('sceneLayerFor'),fn('drawOrderedObjects')].join('\n'),c);
const order=vm.runInContext('drawOrderedObjects',c),bush={kind:'scenery',path:['sprites',0],obj:{}},koopa={kind:'enemy',path:['enemies',0],obj:{}};
assert.deepEqual(order([bush,koopa]).map(x=>x.kind),['scenery','enemy'],'bush placed first stays behind');
assert.deepEqual(order([koopa,bush]).map(x=>x.kind),['scenery','enemy'],'bush placed last stays behind');
bush.obj.sceneLayer='foreground';assert.deepEqual(order([bush,koopa]).map(x=>x.kind),['enemy','scenery'],'foreground override renders bush in front');
const reference=JSON.parse(fs.readFileSync('themes/theme_marioai_reference_pack.llmtheme.txt','utf8'));
assert(reference.objects[reference.placeables.koopaRed.object].attachments.every(x=>x.layer==='behind'),'wing-behind-body remains local composition metadata');
assert(!html.includes('o.sceneLayer=')||!html.includes('attachments.forEach(x=>x.sceneLayer'),'global scene layer does not rewrite attachments');
assert(html.includes('const vis=drawOrderedObjects(visibleObjects())'),'hit-testing reverses visible draw order');
assert(html.indexOf('for(const it of selection.filter(passesFilters)')>html.indexOf('for(const it of drawOrderedObjects(vis))'),'selection UI renders after scene');
assert(!/sceneLayerFor[^]*collisionMode/.test(fn('sceneLayerFor')),'scene layer does not derive from collision');
console.log('editor scene layer tests passed');
